app:
  profile: ${SPRING_PROFILES_ACTIVE}
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5434/tokinonagare"
    username: "tokinonagare"
    password: "Tokinonagare123"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: "validate"
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
spring-doc:
  swagger-ui:
    enabled: true