spring:
  datasource:
    url: "jdbc:postgresql://localhost:5434/tokinonagare"
    username: "tokinonagare"
    password: "Tokinonagare123"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: "validate"
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        globally_quoted_identifiers: true
        jdbc:
          time_zone: GMT-3
spring-doc:
  swagger-ui:
    enabled: true
    defaultModelsExpandDepth: -1 # Hide the model section
paymentTimeLimitFor:
  mercadoPago: 1
  cash: 5