event:
  address: ${EVENT_ADDRESS}
  dateTime: ${EVENT_DATE_TIME}
  name: ${EVENT_NAME}
  place: ${EVENT_PLACE}
spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        jdbc:
          time_zone: GMT-3
  mail:
    host: smtp.gmail.com
    port: 58
    username: A_COMPLETAR@A_COMPLETAR.com
    password: A_COMPLETAR
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
spring-doc:
  swagger-ui:
    defaultModelsExpandDepth: -1 # Hide the model section
payment:
  mercadoPagoAccount: ${PAYMENT_MP_ACCOUNT}
paymentTimeLimitFor:
  mercadoPago: 1
  cash: 5
