event:
  address: ${EVENT_ADDRESS}
  dateTime: ${EVENT_DATE_TIME}
  name: ${EVENT_NAME}
  place: ${EVENT_PLACE}

server:
  port: ${APP_PORT}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: ${DB_DDL_AUTO}
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  mail:
    host: smtp.gmail.com
    port: 587
    username: A_COMPLETAR@A_COMPLETAR.com
    password: A_COMPLETAR
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
spring-doc:
  swagger-ui:
    enabled: ${SWAGGER_ENABLE}
payment:
  mercadoPagoAccount: ${PAYMENT_MP_ACCOUNT}
paymentTimeLimitFor:
  mercadoPago: ${RESERVATION_MERCADOPAGO_EXPIRATION_TIME}
  cash: ${RESERVATION_CASH_EXPIRATION_TIME}