spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        jdbc:
          time_zone: GMT-3
spring-doc:
  swagger-ui:
    defaultModelsExpandDepth: -1 # Hide the model section
paymentTimeLimitFor:
  mercadoPago: 1
  cash: 5