server:
  port: ${APP_PORT} # AWS espera que el puerto se presente por el puerto 5000

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: ${DB_DDL_AUTO}
    open-in-view: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        jdbc:
          time_zone: GMT-3
spring-doc:
  swagger-ui:
    enabled: true
    defaultModelsExpandDepth: -1 # Hide the model section