app:
  profile: TESTING
mail:
  headerImageCanonicalPath: ${MAIL_HEADER_IMAGE_CANONICAL_PATH}
  backupRecipient1: ${MAIL_BACKUP_RECIPIENT1}
  backupRecipient2: ${MAIL_BACKUP_RECIPIENT2}
  backupRecipient3: ${MAIL_BACKUP_RECIPIENT3}
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
spring-doc:
  swagger-ui:
    enabled: true